// Barrel re-export — preserves existing import paths
export { REGION_PRESETS, buildRssUrl, localeContextFor } from './region';
export type { RegionPreset, RssLocale, LocaleContext } from './region';
export { normalizeWhitespace, normalizeTitle, normalizeSource, makeKey } from './normalize';
export { parseRss } from './rss';
export type { RssItem } from './rss';
export { scoreItem, titleSimilarity } from './scoring';
export { scoreImportance, importanceThreshold } from './importance';
export type { ImportanceTier, ImportanceResult } from './importance';
export { escapeRegExp } from './terms';
export { buildDigest, buildDigestWithStats, matchTerms, parsePubDate } from './digest';
export type { DigestItem, BuildDigestOptions } from './digest';
export { emojiFor, renderDigest, renderTopicalDigest } from './render';
export { translateDeepL, DEEPL_API_URL } from './translate';
export type { DeepLTranslation, DeepLResponse } from './translate';
export { readSeenKeys, writeSeenKeys, DEFAULT_STATE_FILE } from './state';
export { runDigest, mergeSeenKeys, runTopicalDigest } from './pipeline';
export type { RunDigestOptions, RunDigestResult, RunTopicalDigestOptions, RunTopicalDigestResult, TopicFetcher, TopicSection } from './pipeline';
export { DEFAULT_CONFIG, loadConfig, resolveConfigPath } from './config/load';
export type { ResolveConfigOptions } from './config/load';
export { DigestConfigSchema, parseConfig } from './config/schema';
export type { DigestConfig, Topic, Locale, Display, MatchMode, Heuristics, ScoringConfig, DedupeConfig, ImportanceConfig, EmojiRule } from './config/schema';
