// Barrel re-export — preserves existing import paths
export { DEFAULT_STATE_FILE, readSeenKeys, writeSeenKeys } from './state';
export { DEEPL_API_URL, translateDeepL } from './translate';
export type { DeepLTranslation, DeepLResponse } from './translate';
export { parseRss } from './pipeline/rss';
export type { RssItem } from './pipeline/rss';
export { selectItems, matchTerms, parsePubDate } from './pipeline/select';
export type { DigestItem, SelectContext, SelectResult } from './pipeline/select';
export { runDigest } from './pipeline/run';
export type { RunOptions, DigestResult, TopicSection, FetchText, Translate } from './pipeline/run';
export { renderText } from './output/text';
export { emojiFor } from './output/emoji';
export { toJson } from './output/json';
export type { DigestJson, DigestJsonItem, JsonMeta } from './output/json';
export { hoursAgo } from './output/time';
export { buildFeedUrl } from './pipeline/url';
export { scoreItem } from './pipeline/scoring';
export { titleSimilarity } from './pipeline/similarity';
export { scoreImportance, importanceThreshold } from './pipeline/importance';
export type { ImportanceTier, ImportanceResult } from './pipeline/importance';
export { normalizeWhitespace, normalizeTitle, normalizeSource, makeKey } from './pipeline/normalize';
export { escapeRegExp } from './pipeline/terms';
export { DEFAULT_CONFIG, loadConfig, resolveConfigPath } from './config/load';
export type { ResolveConfigOptions } from './config/load';
export { DigestConfigSchema, parseConfig } from './config/schema';
export type { DigestConfig, Topic, Locale, Display, MatchMode, Heuristics, ScoringConfig, DedupeConfig, ImportanceConfig, EmojiRule } from './config/schema';
